### ISSUE TITLE
Retrieve error message in web client

### ISSUE THREAD

**Issue by vengadeshg** [lfreeland/Salesforce-Bulk-API-Starter#1]
HI,
   Could you tell how to retrieve the error message when the query fails to run in QueryAccountMethod Test...

**Comment by lfreeland** [comment]
When I get a chance in the next couple of days, I'll take a look at this. I
recently reset my password to my developer org which is where those tests
are running against, if I recall correctly. Ensure that the tests are
running against your own Salesforce org and not mine.

On Wed, Feb 18, 2015 at 5:43 AM, vengadeshg notifications@github.com
wrote:

> HI,
> Could you tell how to retrieve the error message when the query fails to
> run in QueryAccountMethod Test...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lfreeland/Salesforce-Bulk-API-Starter/issues/1.

## 

Luke Freeland
Software Engineer
_Nimble__User_
http://www.google.com/url?q=http%3A%2F%2Fwww.nimbleuser.com&sa=D&sntz=1&usg=AFrqEzcCBokbSHfgDupnUqzaRG8VolytRw
technology.  for people.

656 Kreag Road
Pittsford, NY 14534
Main: 585 586-4750 x134
Direct: 585 454-8734
lfreeland@nimbleuser.com lfreeland@nimbleuser.com

**Comment by vengadeshg** [comment]
Hi,
    Did you verify how to retrieve error message when query fails to run in QueryAccountmethod?

**Comment by phanthienthang** [comment]
Hi vengadeshg,
Thank you for your sharing. I got an issue: "The remote name could not be resolved: 'ap-api.salesforce.com'"
Did you get this issue before? Could you please tell me how did you solve it?

**Comment by vengadeshg** [comment]
Hi phanthienthang,
                            I didnt get any issue like this..

**Comment by phanthienthang** [comment]
Hi vengadeshg,
Thank you for your quick response :+1: . I tested with the other account which have different instance_name (e.g ap2) and it worked fine. Then I make a check with "ping" for both and i got the message :
"Ping request could not find host ap-api.salesforce.com". I have no idea with this message, and still looking for it.

**Comment by cccastle** [comment]
Hi I am getting 
WebException ... {"The remote name could not be resolved: 'emea-api.salesforce.com'"}

**Comment by lfreeland** [comment]
Hey @cccastle, @vengadeshg, and @phanthienthang,

@joel-downey I think fixed the issue with the pod logic so that it'll support custom domains and other Salesforce regions. Let me know how it goes.

Out of curiosity, how are you using the code? Just playing around to learn the bulk api, using it for "work", or for something else?
